### ISSUE TITLE
Использовать synchronized

### ISSUE THREAD

**Issue by amaksoft** [AltarixExercises2016/ahmetov.andrey#1]
В данном конкретном примере это не срашно т.к. есть всего один пишущий поток, однако все равно желательно использовать synchronized при записи в `ArrayList<String> ListWork`.

## Зачем это нужно?

Пример:
Один пишущий поток не справлялся (не зря же мы его в Thread завернули, предусматривали такую возможность) и мы сделали три.
Обычно они хранятся в массивах, мы только в одном месте цифру меняем. Вот так мы и сделали. Что внутри Thread смотреть времени не было т.к. там несколько сотен строк (так обычно и бывает).
В результате получаем три потока, которые неконтролируемо пишут в один и тот же массив. Это может привести к проблемам.

## Как конкретно решается эта проблема?

Например можно использовать [враппер synchronizedList](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList(java.util.List))

**Comment by Andrey092009** [comment]
Добавил синхронизацию.

**Comment by amaksoft** [comment]
Исправлено в коммите [5da6d3d](https://github.com/AltarixExercises2016/ahmetov.andrey/commit/5da6d3dafc31dc0191183bd2ad3e48e0a3391fd9)
Задача закрыта.
